@startuml
title: Create Product Detail Sequence Diagram
actor user
participant BelanjaYukFE
box "BelanjaYuk.id" #LightBlue
participant AppController
participant ProductDetailService
end box

user -> BelanjaYukFE ++ : Create Product Detail menu
BelanjaYukFE -> AppController ++ : /graphql create product detail
    note right of BelanjaYukFE
    content type: application/json
    request body:
        mutation{
          createProductDetail(productDetailInput){
            value
            status
            id
            productStock
            sellingPrice
            purchasePrice
            product
          }
        }

        ProductDetailInput(
            productStockId,
            sellingPrice,
            purchasePrice,
            value,
            productId
        )
    end note
AppController -> AppController : parseGraphql()
AppController -> ProductDetailService ++ : call createProductDetail
    note left
    passing:
    - context
    - productDetailInput
    end note
ProductDetailService --> AppController --: ProductDetail
AppController --> BelanjaYukFE -- : ProductDetail
BelanjaYukFE --> user -- : create successfull and view productDetail
@enduml